window.RESPUESTAS_PINTADAS = {
  jornada: { imagenes: [], tt: { texto:"7h /jornada" }, sdf:{ texto:"7h /jornada" }, nocturno:{ texto:"Es voluntario y no rotativo. Si no hubiera personal voluntario para el turno de noche se cubrirán los puestos necesarios con personal de día rotando entre todos ellos, excepto de mayores de 60 años, que será voluntario." }, 
  requisitos:{ texto:"Mayor de 18 años y voluntario para mayores de 60 años" }, anual:{ texto:"Para el cálculo de la jornada anual se tendrán en cuenta los festivos de cada año y las vacaciones, asi como el permiso de navidad de 2 días para jornada completa y 1 día para jornada de SDF" }, 
  irregular:{ texto:"No aplica" }, cambios:{ texto:"Se realizarán por hoja de solicitud. Si se solicita voluntario la empresa podra aceptar dicho cambiom, o no. Si se solicita por conciliación familiar se debera aportar documentación para acreditarlo" }, efectivas:{ texto:"Todas aquellas horas dentro de la jornada laboral incluidas las horas de cobro" }, 
  bocadillo:{ texto:"Se dispondra de 30 minutos para todas las jornadas y turnos" }, complementarias:{ texto:"Tambien llamadas horas extras o jornada extra" } },
  vacaciones: { imagenes: [], tt:{ texto:"31 días naturales de vacaciones" }, sdf:{ texto:"10 dias habiles" }, computo:{ texto:"Dias naturales." }, devengo:{ texto:"Se disfrutaran las vacaciones anuales excepto en contratos temporales que se disfrutaran la parte proporcional trabajado desde el 1 de enero de ese mismo año." }, 
               disfrute:{ texto:"Se disfurtaran en el mes de julio o agosto. Cualquier cambio se solicitará por hoja de solicitud." }, calendario:{ texto:"No aplica" }, antiguedad:{ texto:"No procede, se asignará por rotación" } },
  permisos: { imagenes: [], retribuidos:{ texto:"" }, noretribuidos:{ texto:"" }, hospitalizacion:{ texto:"" }, fallecimiento:{ texto:"" }, nacimiento:{ texto:"" }, acompanamiento:{ texto:"" }, deber:{ texto:"" } },
  pluses: { imagenes: [], nocturnidad:{ texto:"" }, festividad:{ texto:"" }, peligrosidad:{ texto:"" }, turnicidad:{ texto:"" }, transporte:{ texto:"" }, asistencia:{ texto:"" } },
  descansos: { imagenes: [], semanal:{ texto:"" }, diario:{ texto:"" }, festivos:{ texto:"" }, recuperaciones:{ texto:"" } },
  antiguedad: { imagenes: [], trienios:{ texto:"" }, quinquenios:{ texto:"" } },
  pagas: { imagenes: [], verano:{ texto:"" }, navidad:{ texto:"" }, prorrateo:{ texto:"" } },
  economia: { imagenes: [], salario:{ texto:"" }, complementos:{ texto:"" }, dietas:{ texto:"" }, kilometraje:{ texto:"" } },
  excedencias: { imagenes: [], voluntaria:{ texto:"" }, forzosa:{ texto:"" }, cuidado:{ texto:"" } },
  conductores: { imagenes: [], carnet:{ texto:"" }, funciones:{ texto:"" }, plus:{ texto:"" } },
  ascensos: { imagenes: [], criterios:{ texto:"" }, pruebas:{ texto:"" } },
  contratacion: { imagenes: [], indefinido:{ texto:"" }, temporal:{ texto:"" }, formacion:{ texto:"" } },
  vacantes: { imagenes: [], asignacion:{ texto:"" }, movilidad:{ texto:"" } },
  prendas: { imagenes: [], entrega:{ texto:"" }, reposicion:{ texto:"" }, temporada:{ texto:"" } },
  mejoras: { imagenes: [], seguro:{ texto:"" }, ayudas:{ texto:"" }, formacion:{ texto:"" } },
  jubilacion: { imagenes: [], parcial:{ texto:"" }, anticipada:{ texto:"" } },
  seguridad: { imagenes: [], epis:{ texto:"" }, riesgos:{ texto:"" }, reconocimientos:{ texto:"" } },
  adicionales: { imagenes: [], primera:{ texto:"" }, segunda:{ texto:"" }, tercera:{ texto:"" } }
};
